-- CreateTable
CREATE TABLE `m_debitur_jadwal` (
    `JADWAL_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `DEBITUR_KREDIT_ID` INTEGER NOT NULL,
    `ANGSURAN_KE` INTEGER NOT NULL,
    `TGL_JATUH_TEMPO` DATE NOT NULL,
    `POKOK` DECIMAL(19, 4) NOT NULL,
    `BUNGA` DECIMAL(19, 4) NOT NULL,
    `TOTAL_ANGSURAN` DECIMAL(19, 4) NOT NULL,
    `SISA_POKOK` DECIMAL(19, 4) NOT NULL,
    `STATUS` VARCHAR(20) NOT NULL DEFAULT 'UNPAID',
    `TGL_BAYAR` DATE NULL,
    `CREATE_WHO` VARCHAR(50) NULL,
    `CREATE_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CHANGE_WHO` VARCHAR(50) NULL,
    `CHANGE_DATE` DATETIME(3) NULL,

    PRIMARY KEY (`JADWAL_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `m_debitur_jadwal` ADD CONSTRAINT `m_debitur_jadwal_DEBITUR_KREDIT_ID_fkey` FOREIGN KEY (`DEBITUR_KREDIT_ID`) REFERENCES `m_debitur_kredit`(`DEBITUR_KREDIT_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
