/*
  Warnings:

  - You are about to drop the column `BAYAR_BUNGA` on the `m_debitur_jadwal` table. All the data in the column will be lost.
  - You are about to drop the column `BAYAR_DENDA` on the `m_debitur_jadwal` table. All the data in the column will be lost.
  - You are about to drop the column `BAYAR_POKOK` on the `m_debitur_jadwal` table. All the data in the column will be lost.
  - You are about to drop the column `DENDA` on the `m_debitur_jadwal` table. All the data in the column will be lost.
  - You are about to drop the column `TOTAL_BAYAR` on the `m_debitur_jadwal` table. All the data in the column will be lost.

*/
-- AlterTable
ALTER TABLE `m_debitur_jadwal` DROP COLUMN `BAYAR_BUNGA`,
    DROP COLUMN `BAYAR_DENDA`,
    DROP COLUMN `BAYAR_POKOK`,
    DROP COLUMN `DENDA`,
    DROP COLUMN `TOTAL_BAYAR`,
    ADD COLUMN `SISA_BUNGA` DECIMAL(19, 4) NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `t_trans_kredit` MODIFY `TGL_TRANS` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- CreateTable
CREATE TABLE `m_nasabah_modal` (
    `NO_REK_MODAL` VARCHAR(50) NOT NULL,
    `NASABAH_ID` INTEGER NOT NULL,
    `TGL_BUKA` DATE NOT NULL,
    `SALDO` DECIMAL(19, 4) NOT NULL DEFAULT 0,
    `STATUS` VARCHAR(10) NOT NULL DEFAULT 'A',
    `WILAYAH_CD` VARCHAR(10) NULL,
    `CREATE_WHO` VARCHAR(50) NULL,
    `CREATE_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CHANGE_WHO` VARCHAR(50) NULL,
    `CHANGE_DATE` DATETIME(3) NULL,

    PRIMARY KEY (`NO_REK_MODAL`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `t_trans_modal` (
    `TRANS_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NO_REK_MODAL` VARCHAR(50) NOT NULL,
    `TIPE_TRANS` VARCHAR(10) NOT NULL,
    `TGL_TRANS` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `NOMINAL` DECIMAL(19, 4) NOT NULL,
    `SALDO_AKHIR` DECIMAL(19, 4) NOT NULL,
    `KETERANGAN` TEXT NULL,
    `JOURNAL_ID` INTEGER NULL,
    `CREATE_WHO` VARCHAR(50) NULL,
    `CREATE_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`TRANS_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `m_pinjaman_external` (
    `LOAN_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `BANK_NAME` VARCHAR(100) NOT NULL,
    `CONTRACT_NUMBER` VARCHAR(50) NOT NULL,
    `LOAN_DATE` DATE NOT NULL,
    `MATURITY_DATE` DATE NOT NULL,
    `PRINCIPAL` DECIMAL(19, 4) NOT NULL,
    `INTEREST_RATE` DECIMAL(5, 2) NOT NULL,
    `TERM_MONTHS` INTEGER NOT NULL,
    `INSTALLMENT_TYPE` VARCHAR(20) NOT NULL,
    `MONTHLY_INSTALLMENT` DECIMAL(19, 4) NOT NULL,
    `OUTSTANDING_PRINCIPAL` DECIMAL(19, 4) NOT NULL,
    `STATUS` VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    `CREATE_WHO` VARCHAR(50) NULL,
    `CREATE_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CHANGE_WHO` VARCHAR(50) NULL,
    `CHANGE_DATE` DATETIME(3) NULL,

    PRIMARY KEY (`LOAN_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `t_jadwal_pinjaman_external` (
    `SCHEDULE_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `LOAN_ID` INTEGER NOT NULL,
    `INSTALLMENT_NUMBER` INTEGER NOT NULL,
    `DUE_DATE` DATE NOT NULL,
    `PRINCIPAL_DUE` DECIMAL(19, 4) NOT NULL,
    `INTEREST_DUE` DECIMAL(19, 4) NOT NULL,
    `TOTAL_DUE` DECIMAL(19, 4) NOT NULL,
    `STATUS` VARCHAR(20) NOT NULL DEFAULT 'DUE',
    `PAID_DATE` DATE NULL,

    PRIMARY KEY (`SCHEDULE_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `t_period_lock` (
    `PERIODE` VARCHAR(7) NOT NULL,
    `STATUS` VARCHAR(20) NOT NULL,
    `REASON` TEXT NULL,
    `LOCKED_AT` DATETIME(3) NOT NULL,
    `LOCKED_BY` INTEGER NOT NULL,
    `UNLOCKED_AT` DATETIME(3) NULL,
    `UNLOCKED_BY` INTEGER NULL,
    `UNLOCK_REASON` TEXT NULL,

    PRIMARY KEY (`PERIODE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `t_unlock_request` (
    `REQUEST_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PERIODE` VARCHAR(7) NOT NULL,
    `REQUESTED_BY` INTEGER NOT NULL,
    `REQUESTED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `REASON` TEXT NOT NULL,
    `STATUS` VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    `APPROVED_BY` INTEGER NULL,
    `APPROVED_AT` DATETIME(3) NULL,
    `MANAGER_NOTES` TEXT NULL,

    PRIMARY KEY (`REQUEST_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `t_month_end_log` (
    `LOG_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PERIODE` VARCHAR(7) NOT NULL,
    `ACTION` VARCHAR(50) NOT NULL,
    `STATUS` VARCHAR(20) NOT NULL,
    `DETAILS` TEXT NULL,
    `PERFORMED_BY` INTEGER NOT NULL,
    `PERFORMED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`LOG_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `t_aktiva_penyusutan` ADD CONSTRAINT `t_aktiva_penyusutan_JOURNAL_ID_fkey` FOREIGN KEY (`JOURNAL_ID`) REFERENCES `t_posted_journal`(`JOURNAL_ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `m_nasabah_modal` ADD CONSTRAINT `m_nasabah_modal_NASABAH_ID_fkey` FOREIGN KEY (`NASABAH_ID`) REFERENCES `m_nasabah`(`NASABAH_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `t_trans_modal` ADD CONSTRAINT `t_trans_modal_NO_REK_MODAL_fkey` FOREIGN KEY (`NO_REK_MODAL`) REFERENCES `m_nasabah_modal`(`NO_REK_MODAL`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `t_jadwal_pinjaman_external` ADD CONSTRAINT `t_jadwal_pinjaman_external_LOAN_ID_fkey` FOREIGN KEY (`LOAN_ID`) REFERENCES `m_pinjaman_external`(`LOAN_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `t_period_lock` ADD CONSTRAINT `t_period_lock_LOCKED_BY_fkey` FOREIGN KEY (`LOCKED_BY`) REFERENCES `s_user_lpd`(`USER_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `t_period_lock` ADD CONSTRAINT `t_period_lock_UNLOCKED_BY_fkey` FOREIGN KEY (`UNLOCKED_BY`) REFERENCES `s_user_lpd`(`USER_ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `t_unlock_request` ADD CONSTRAINT `t_unlock_request_PERIODE_fkey` FOREIGN KEY (`PERIODE`) REFERENCES `t_period_lock`(`PERIODE`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `t_unlock_request` ADD CONSTRAINT `t_unlock_request_REQUESTED_BY_fkey` FOREIGN KEY (`REQUESTED_BY`) REFERENCES `s_user_lpd`(`USER_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `t_unlock_request` ADD CONSTRAINT `t_unlock_request_APPROVED_BY_fkey` FOREIGN KEY (`APPROVED_BY`) REFERENCES `s_user_lpd`(`USER_ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `t_month_end_log` ADD CONSTRAINT `t_month_end_log_PERFORMED_BY_fkey` FOREIGN KEY (`PERFORMED_BY`) REFERENCES `s_user_lpd`(`USER_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
