-- AlterTable
ALTER TABLE `s_user_lpd` ADD COLUMN `IS_TOTP_ENABLED` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `TOTP_SECRET` VARCHAR(100) NULL;

-- CreateTable
CREATE TABLE `t_collector_shift` (
    `SHIFT_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `USER_ID` INTEGER NOT NULL,
    `SHIFT_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `START_TIME` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `END_TIME` DATETIME(3) NULL,
    `STATUS` VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    `STARTING_CASH` DECIMAL(19, 4) NOT NULL,
    `START_100K` INTEGER NOT NULL DEFAULT 0,
    `START_50K` INTEGER NOT NULL DEFAULT 0,
    `START_20K` INTEGER NOT NULL DEFAULT 0,
    `START_10K` INTEGER NOT NULL DEFAULT 0,
    `START_5K` INTEGER NOT NULL DEFAULT 0,
    `START_2K` INTEGER NOT NULL DEFAULT 0,
    `START_1K` INTEGER NOT NULL DEFAULT 0,
    `START_500` INTEGER NOT NULL DEFAULT 0,
    `START_200` INTEGER NOT NULL DEFAULT 0,
    `START_100` INTEGER NOT NULL DEFAULT 0,
    `ENDING_CASH` DECIMAL(19, 4) NULL,
    `END_100K` INTEGER NULL,
    `END_50K` INTEGER NULL,
    `END_20K` INTEGER NULL,
    `END_10K` INTEGER NULL,
    `END_5K` INTEGER NULL,
    `END_2K` INTEGER NULL,
    `END_1K` INTEGER NULL,
    `END_500` INTEGER NULL,
    `END_200` INTEGER NULL,
    `END_100` INTEGER NULL,
    `TOTAL_DEPOSITS` DECIMAL(19, 4) NOT NULL DEFAULT 0,
    `TOTAL_WITHDRAWALS` DECIMAL(19, 4) NOT NULL DEFAULT 0,
    `TRANS_COUNT` INTEGER NOT NULL DEFAULT 0,
    `CLOSING_JOURNAL_ID` INTEGER NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NOT NULL,

    INDEX `idx_shift_user_status`(`USER_ID`, `STATUS`),
    INDEX `idx_shift_date`(`SHIFT_DATE`),
    PRIMARY KEY (`SHIFT_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `t_collector_shift` ADD CONSTRAINT `t_collector_shift_USER_ID_fkey` FOREIGN KEY (`USER_ID`) REFERENCES `s_user_lpd`(`USER_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
