-- CreateTable
CREATE TABLE `s_user_lpd` (
    `USER_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `LOGIN` VARCHAR(50) NOT NULL,
    `PWD` VARCHAR(255) NOT NULL,
    `NAMA` VARCHAR(100) NOT NULL,
    `STAFF_ID` VARCHAR(50) NULL,
    `ROLE_LPD_ID` INTEGER NOT NULL,
    `WILAYAH_CD` VARCHAR(20) NULL,
    `TOKEN` TEXT NULL,
    `ACTIVE_FLAG` BOOLEAN NOT NULL DEFAULT true,
    `CREATE_WHO` VARCHAR(50) NULL,
    `CREATE_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CHANGE_WHO` VARCHAR(50) NULL,
    `CHANGE_DATE` DATETIME(3) NULL,

    UNIQUE INDEX `s_user_lpd_LOGIN_key`(`LOGIN`),
    PRIMARY KEY (`USER_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `s_role_lpd` (
    `ROLE_LPD_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `nama_role` VARCHAR(100) NOT NULL,
    `deskripsi` TEXT NULL,
    `ACTIVE_FLAG` BOOLEAN NOT NULL DEFAULT true,
    `CREATE_WHO` VARCHAR(50) NULL,
    `CREATE_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CHANGE_WHO` VARCHAR(50) NULL,
    `CHANGE_DATE` DATETIME(3) NULL,

    PRIMARY KEY (`ROLE_LPD_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `s_menu_lpd` (
    `menu_lpd_id` INTEGER NOT NULL AUTO_INCREMENT,
    `nama_menu` VARCHAR(100) NOT NULL,
    `modul` VARCHAR(50) NULL,
    `node` VARCHAR(10) NULL,
    `parent_id` INTEGER NULL,
    `icon` VARCHAR(50) NULL,
    `path` VARCHAR(255) NULL,
    `order_num` INTEGER NULL,
    `ACTIVE_FLAG` BOOLEAN NOT NULL DEFAULT true,
    `CREATE_WHO` VARCHAR(50) NULL,
    `CREATE_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CHANGE_WHO` VARCHAR(50) NULL,
    `CHANGE_DATE` DATETIME(3) NULL,

    PRIMARY KEY (`menu_lpd_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `s_menu_role_lpd` (
    `ROLE_LPD_ID` INTEGER NOT NULL,
    `menu_lpd_id` INTEGER NOT NULL,

    PRIMARY KEY (`ROLE_LPD_ID`, `menu_lpd_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `s_lov_value` (
    `CODE` VARCHAR(50) NOT NULL,
    `CODE_VAL` VARCHAR(50) NOT NULL,
    `DESCRIPTION` VARCHAR(255) NULL,
    `ORDER_NUM` INTEGER NULL,
    `ACTIVE_FLAG` BOOLEAN NOT NULL DEFAULT true,
    `CREATE_WHO` VARCHAR(50) NULL,
    `CREATE_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CHANGE_WHO` VARCHAR(50) NULL,
    `CHANGE_DATE` DATETIME(3) NULL,

    PRIMARY KEY (`CODE`, `CODE_VAL`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `m_nasabah` (
    `NASABAH_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAMA` VARCHAR(255) NOT NULL,
    `NO_KTP` VARCHAR(50) NULL,
    `ALAMAT` TEXT NULL,
    `EMAIL` VARCHAR(100) NULL,
    `TELEPON` VARCHAR(20) NULL,
    `TEMPAT_LAHIR` VARCHAR(100) NULL,
    `TANGGAL_LAHIR` DATE NULL,
    `JENIS_KELAMIN` VARCHAR(1) NULL,
    `PEKERJAAN` VARCHAR(100) NULL,
    `FILE_KTP` VARCHAR(255) NULL,
    `FILE_KK` VARCHAR(255) NULL,
    `ACTIVE_FLAG` BOOLEAN NOT NULL DEFAULT true,
    `CREATE_WHO` VARCHAR(50) NULL,
    `CREATE_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CHANGE_WHO` VARCHAR(50) NULL,
    `CHANGE_DATE` DATETIME(3) NULL,

    UNIQUE INDEX `m_nasabah_NO_KTP_key`(`NO_KTP`),
    PRIMARY KEY (`NASABAH_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `m_nasabah_anggota` (
    `NO_ANGGOTA` VARCHAR(20) NOT NULL,
    `NASABAH_ID` INTEGER NOT NULL,
    `POKOK` DECIMAL(19, 4) NOT NULL,
    `WAJIB_AWAL` DECIMAL(19, 4) NOT NULL,
    `TGL_DAFTAR` DATE NOT NULL,
    `TGL_TUTUP` DATE NULL,
    `SALDO` DECIMAL(19, 4) NOT NULL DEFAULT 0,
    `STATUS` VARCHAR(2) NOT NULL DEFAULT 'D',
    `WILAYAH_CD` VARCHAR(45) NOT NULL,
    `GROUP_CD` VARCHAR(10) NOT NULL,
    `REMARK` TEXT NULL,
    `POTONGAN` DECIMAL(19, 4) NOT NULL DEFAULT 0,
    `ACTIVE_FLAG` BOOLEAN NOT NULL DEFAULT true,
    `CREATE_WHO` VARCHAR(50) NOT NULL,
    `CREATE_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`NO_ANGGOTA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `m_nasabah_tab` (
    `NO_TAB` VARCHAR(50) NOT NULL,
    `NASABAH_ID` INTEGER NOT NULL,
    `TGL_BUKA` DATE NOT NULL,
    `SALDO` DECIMAL(19, 4) NOT NULL DEFAULT 0,
    `BUNGA_PCT` DECIMAL(5, 2) NOT NULL DEFAULT 0,
    `STATUS` VARCHAR(10) NOT NULL DEFAULT 'A',
    `CREATE_WHO` VARCHAR(50) NULL,
    `CREATE_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CHANGE_WHO` VARCHAR(50) NULL,
    `CHANGE_DATE` DATETIME(3) NULL,

    PRIMARY KEY (`NO_TAB`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `m_nasabah_jangka` (
    `NO_JANGKA` VARCHAR(50) NOT NULL,
    `NASABAH_ID` INTEGER NOT NULL,
    `TGL_BUKA` DATE NOT NULL,
    `END_DATE` DATE NOT NULL,
    `NOMINAL` DECIMAL(19, 4) NOT NULL,
    `BUNGA` DECIMAL(5, 2) NOT NULL,
    `PAYOUT_MODE` VARCHAR(20) NOT NULL DEFAULT 'MATURITY',
    `TARGET_ACCOUNT_ID` VARCHAR(50) NULL,
    `STATUS` VARCHAR(10) NOT NULL DEFAULT 'A',
    `CREATE_WHO` VARCHAR(50) NULL,
    `CREATE_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CHANGE_WHO` VARCHAR(50) NULL,
    `CHANGE_DATE` DATETIME(3) NULL,

    PRIMARY KEY (`NO_JANGKA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `m_nasabah_brahmacari` (
    `NO_BRAHMACARI` VARCHAR(50) NOT NULL,
    `NASABAH_ID` INTEGER NOT NULL,
    `TGL_BUKA` DATE NOT NULL,
    `SALDO` DECIMAL(19, 4) NOT NULL DEFAULT 0,
    `BUNGA_PCT` DECIMAL(5, 2) NOT NULL DEFAULT 0,
    `STATUS` VARCHAR(10) NOT NULL DEFAULT 'A',
    `CREATE_WHO` VARCHAR(50) NULL,
    `CREATE_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CHANGE_WHO` VARCHAR(50) NULL,
    `CHANGE_DATE` DATETIME(3) NULL,

    PRIMARY KEY (`NO_BRAHMACARI`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `m_nasabah_balimesari` (
    `NO_BALIMESARI` VARCHAR(50) NOT NULL,
    `NASABAH_ID` INTEGER NOT NULL,
    `TGL_BUKA` DATE NOT NULL,
    `SALDO` DECIMAL(19, 4) NOT NULL DEFAULT 0,
    `BUNGA_PCT` DECIMAL(5, 2) NOT NULL DEFAULT 0,
    `STATUS` VARCHAR(10) NOT NULL DEFAULT 'A',
    `CREATE_WHO` VARCHAR(50) NULL,
    `CREATE_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CHANGE_WHO` VARCHAR(50) NULL,
    `CHANGE_DATE` DATETIME(3) NULL,

    PRIMARY KEY (`NO_BALIMESARI`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `m_nasabah_wanaprasta` (
    `NO_WANAPRASTA` VARCHAR(50) NOT NULL,
    `NASABAH_ID` INTEGER NOT NULL,
    `TGL_BUKA` DATE NOT NULL,
    `SALDO` DECIMAL(19, 4) NOT NULL DEFAULT 0,
    `BUNGA_PCT` DECIMAL(5, 2) NOT NULL DEFAULT 0,
    `STATUS` VARCHAR(10) NOT NULL DEFAULT 'A',
    `CREATE_WHO` VARCHAR(50) NULL,
    `CREATE_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CHANGE_WHO` VARCHAR(50) NULL,
    `CHANGE_DATE` DATETIME(3) NULL,

    PRIMARY KEY (`NO_WANAPRASTA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `m_nasabah_waris` (
    `WARIS_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NASABAH_ID` INTEGER NOT NULL,
    `NAMA_WARIS` VARCHAR(255) NOT NULL,
    `HUBUNGAN` VARCHAR(50) NOT NULL,
    `ALAMAT` TEXT NULL,
    `TELEPON` VARCHAR(20) NULL,
    `CREATE_WHO` VARCHAR(50) NULL,
    `CREATE_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CHANGE_WHO` VARCHAR(50) NULL,
    `CHANGE_DATE` DATETIME(3) NULL,

    PRIMARY KEY (`WARIS_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `m_debitur_kredit` (
    `DEBITUR_KREDIT_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NASABAH_ID` INTEGER NOT NULL,
    `NOMOR_KREDIT` VARCHAR(50) NULL,
    `JENIS_KREDIT` VARCHAR(50) NOT NULL,
    `TUJUAN_KREDIT` TEXT NULL,
    `NOMINAL_PENGAJUAN` DECIMAL(19, 4) NOT NULL,
    `STATUS` VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    `TGL_PENGAJUAN` DATE NOT NULL,
    `CREATE_WHO` VARCHAR(50) NULL,
    `CREATE_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CHANGE_WHO` VARCHAR(50) NULL,
    `CHANGE_DATE` DATETIME(3) NULL,

    UNIQUE INDEX `m_debitur_kredit_NOMOR_KREDIT_key`(`NOMOR_KREDIT`),
    PRIMARY KEY (`DEBITUR_KREDIT_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `m_debitur_fasilitas` (
    `FASILITAS_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `DEBITUR_KREDIT_ID` INTEGER NOT NULL,
    `NOMINAL` DECIMAL(19, 4) NOT NULL,
    `BUNGA` DECIMAL(5, 2) NOT NULL,
    `JANGKA_WAKTU` INTEGER NOT NULL,
    `ANGSURAN_POKOK` DECIMAL(19, 4) NOT NULL,
    `ANGSURAN_BUNGA` DECIMAL(19, 4) NOT NULL,
    `CREATE_WHO` VARCHAR(50) NULL,
    `CREATE_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CHANGE_WHO` VARCHAR(50) NULL,
    `CHANGE_DATE` DATETIME(3) NULL,

    PRIMARY KEY (`FASILITAS_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `m_debitur_realisasi` (
    `REALISASI_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `DEBITUR_KREDIT_ID` INTEGER NOT NULL,
    `TGL_REALISASI` DATE NOT NULL,
    `NOMINAL_REALISASI` DECIMAL(19, 4) NOT NULL,
    `REKENING` VARCHAR(50) NULL,
    `CREATE_WHO` VARCHAR(50) NULL,
    `CREATE_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CHANGE_WHO` VARCHAR(50) NULL,
    `CHANGE_DATE` DATETIME(3) NULL,

    PRIMARY KEY (`REALISASI_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `m_journal_account` (
    `ACCOUNT_CD` VARCHAR(20) NOT NULL,
    `ACCOUNT_NAME` VARCHAR(255) NOT NULL,
    `ACCOUNT_TYPE` VARCHAR(50) NOT NULL,
    `PARENT_CD` VARCHAR(20) NULL,
    `DEBET_POLE_FLAG` BOOLEAN NOT NULL DEFAULT true,
    `REMARK` TEXT NULL,
    `WILAYAH_CD` VARCHAR(10) NULL,
    `ACTIVE_FLAG` BOOLEAN NOT NULL DEFAULT true,
    `CREATE_WHO` VARCHAR(50) NULL,
    `CREATE_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CHANGE_WHO` VARCHAR(50) NULL,
    `CHANGE_DATE` DATETIME(3) NULL,

    PRIMARY KEY (`ACCOUNT_CD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `t_posted_journal` (
    `JOURNAL_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `JOURNAL_NO` VARCHAR(30) NOT NULL,
    `TGL_POSTING` DATE NOT NULL,
    `KETERANGAN` TEXT NULL,
    `POSTING_TYPE` VARCHAR(10) NOT NULL DEFAULT 'AUTO',
    `TRANS_TYPE` VARCHAR(30) NULL,
    `REF_ID` INTEGER NULL,
    `USER_ID` INTEGER NOT NULL,
    `TELLER_ID` VARCHAR(20) NULL,
    `WILAYAH_CD` VARCHAR(10) NULL,
    `STATUS` VARCHAR(20) NOT NULL DEFAULT 'POSTED',
    `CREATE_WHO` VARCHAR(50) NULL,
    `CREATE_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CHANGE_WHO` VARCHAR(50) NULL,
    `CHANGE_DATE` DATETIME(3) NULL,

    UNIQUE INDEX `t_posted_journal_JOURNAL_NO_key`(`JOURNAL_NO`),
    PRIMARY KEY (`JOURNAL_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `t_posted_journal_detail` (
    `DETAIL_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `JOURNAL_ID` INTEGER NOT NULL,
    `ACCOUNT_CD` VARCHAR(20) NOT NULL,
    `DEBIT` DECIMAL(19, 4) NOT NULL DEFAULT 0,
    `CREDIT` DECIMAL(19, 4) NOT NULL DEFAULT 0,
    `KETERANGAN` TEXT NULL,

    PRIMARY KEY (`DETAIL_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `m_product_coa_mapping` (
    `MAPPING_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `MODULE` VARCHAR(20) NOT NULL,
    `TRANS_TYPE` VARCHAR(30) NOT NULL,
    `DESCRIPTION` VARCHAR(100) NOT NULL,
    `DEBIT_ACCOUNT_CD` VARCHAR(20) NOT NULL,
    `CREDIT_ACCOUNT_CD` VARCHAR(20) NOT NULL,
    `CHANGE_DATE` DATETIME(3) NOT NULL,

    UNIQUE INDEX `m_product_coa_mapping_TRANS_TYPE_key`(`TRANS_TYPE`),
    PRIMARY KEY (`MAPPING_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `t_trans_anggota` (
    `TRANS_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NO_ANGGOTA` VARCHAR(20) NOT NULL,
    `TGL_TRANS` DATETIME(3) NOT NULL,
    `TIPE_TRANS` VARCHAR(20) NOT NULL,
    `NOMINAL` DECIMAL(19, 4) NOT NULL,
    `SALDO_AKHIR` DECIMAL(19, 4) NOT NULL,
    `KETERANGAN` TEXT NULL,
    `USER_ID` INTEGER NOT NULL,
    `CREATE_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`TRANS_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `t_trans_tab` (
    `TRANS_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NO_TAB` VARCHAR(50) NOT NULL,
    `TIPE_TRANS` VARCHAR(10) NOT NULL,
    `NOMINAL` DECIMAL(19, 4) NOT NULL,
    `SALDO_AKHIR` DECIMAL(19, 4) NOT NULL,
    `KETERANGAN` TEXT NULL,
    `CREATE_WHO` VARCHAR(50) NULL,
    `CREATE_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`TRANS_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `t_trans_jangka` (
    `TRANS_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NO_JANGKA` VARCHAR(50) NOT NULL,
    `TIPE_TRANS` VARCHAR(10) NOT NULL,
    `NOMINAL` DECIMAL(19, 4) NOT NULL,
    `KETERANGAN` TEXT NULL,
    `CREATE_WHO` VARCHAR(50) NULL,
    `CREATE_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`TRANS_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `t_trans_brahmacari` (
    `TRANS_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NO_BRAHMACARI` VARCHAR(50) NOT NULL,
    `TIPE_TRANS` VARCHAR(10) NOT NULL,
    `NOMINAL` DECIMAL(19, 4) NOT NULL,
    `SALDO_AKHIR` DECIMAL(19, 4) NOT NULL,
    `KETERANGAN` TEXT NULL,
    `CREATE_WHO` VARCHAR(50) NULL,
    `CREATE_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`TRANS_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `t_trans_balimesari` (
    `TRANS_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NO_BALIMESARI` VARCHAR(50) NOT NULL,
    `TIPE_TRANS` VARCHAR(10) NOT NULL,
    `NOMINAL` DECIMAL(19, 4) NOT NULL,
    `SALDO_AKHIR` DECIMAL(19, 4) NOT NULL,
    `KETERANGAN` TEXT NULL,
    `CREATE_WHO` VARCHAR(50) NULL,
    `CREATE_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`TRANS_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `t_trans_wanaprasta` (
    `TRANS_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NO_WANAPRASTA` VARCHAR(50) NOT NULL,
    `TIPE_TRANS` VARCHAR(10) NOT NULL,
    `NOMINAL` DECIMAL(19, 4) NOT NULL,
    `SALDO_AKHIR` DECIMAL(19, 4) NOT NULL,
    `KETERANGAN` TEXT NULL,
    `CREATE_WHO` VARCHAR(50) NULL,
    `CREATE_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`TRANS_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `t_trans_kredit` (
    `TRANS_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `DEBITUR_KREDIT_ID` INTEGER NOT NULL,
    `TIPE_TRANS` VARCHAR(10) NOT NULL,
    `NOMINAL` DECIMAL(19, 4) NOT NULL,
    `KETERANGAN` TEXT NULL,
    `CREATE_WHO` VARCHAR(50) NULL,
    `CREATE_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`TRANS_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `s_user_lpd` ADD CONSTRAINT `s_user_lpd_ROLE_LPD_ID_fkey` FOREIGN KEY (`ROLE_LPD_ID`) REFERENCES `s_role_lpd`(`ROLE_LPD_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `s_menu_role_lpd` ADD CONSTRAINT `s_menu_role_lpd_ROLE_LPD_ID_fkey` FOREIGN KEY (`ROLE_LPD_ID`) REFERENCES `s_role_lpd`(`ROLE_LPD_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `s_menu_role_lpd` ADD CONSTRAINT `s_menu_role_lpd_menu_lpd_id_fkey` FOREIGN KEY (`menu_lpd_id`) REFERENCES `s_menu_lpd`(`menu_lpd_id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `m_nasabah_anggota` ADD CONSTRAINT `m_nasabah_anggota_NASABAH_ID_fkey` FOREIGN KEY (`NASABAH_ID`) REFERENCES `m_nasabah`(`NASABAH_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `m_nasabah_tab` ADD CONSTRAINT `m_nasabah_tab_NASABAH_ID_fkey` FOREIGN KEY (`NASABAH_ID`) REFERENCES `m_nasabah`(`NASABAH_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `m_nasabah_jangka` ADD CONSTRAINT `m_nasabah_jangka_NASABAH_ID_fkey` FOREIGN KEY (`NASABAH_ID`) REFERENCES `m_nasabah`(`NASABAH_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `m_nasabah_brahmacari` ADD CONSTRAINT `m_nasabah_brahmacari_NASABAH_ID_fkey` FOREIGN KEY (`NASABAH_ID`) REFERENCES `m_nasabah`(`NASABAH_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `m_nasabah_balimesari` ADD CONSTRAINT `m_nasabah_balimesari_NASABAH_ID_fkey` FOREIGN KEY (`NASABAH_ID`) REFERENCES `m_nasabah`(`NASABAH_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `m_nasabah_wanaprasta` ADD CONSTRAINT `m_nasabah_wanaprasta_NASABAH_ID_fkey` FOREIGN KEY (`NASABAH_ID`) REFERENCES `m_nasabah`(`NASABAH_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `m_nasabah_waris` ADD CONSTRAINT `m_nasabah_waris_NASABAH_ID_fkey` FOREIGN KEY (`NASABAH_ID`) REFERENCES `m_nasabah`(`NASABAH_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `m_debitur_kredit` ADD CONSTRAINT `m_debitur_kredit_NASABAH_ID_fkey` FOREIGN KEY (`NASABAH_ID`) REFERENCES `m_nasabah`(`NASABAH_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `m_debitur_fasilitas` ADD CONSTRAINT `m_debitur_fasilitas_DEBITUR_KREDIT_ID_fkey` FOREIGN KEY (`DEBITUR_KREDIT_ID`) REFERENCES `m_debitur_kredit`(`DEBITUR_KREDIT_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `m_debitur_realisasi` ADD CONSTRAINT `m_debitur_realisasi_DEBITUR_KREDIT_ID_fkey` FOREIGN KEY (`DEBITUR_KREDIT_ID`) REFERENCES `m_debitur_kredit`(`DEBITUR_KREDIT_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `t_posted_journal` ADD CONSTRAINT `t_posted_journal_USER_ID_fkey` FOREIGN KEY (`USER_ID`) REFERENCES `s_user_lpd`(`USER_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `t_posted_journal_detail` ADD CONSTRAINT `t_posted_journal_detail_JOURNAL_ID_fkey` FOREIGN KEY (`JOURNAL_ID`) REFERENCES `t_posted_journal`(`JOURNAL_ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `t_posted_journal_detail` ADD CONSTRAINT `t_posted_journal_detail_ACCOUNT_CD_fkey` FOREIGN KEY (`ACCOUNT_CD`) REFERENCES `m_journal_account`(`ACCOUNT_CD`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `m_product_coa_mapping` ADD CONSTRAINT `m_product_coa_mapping_DEBIT_ACCOUNT_CD_fkey` FOREIGN KEY (`DEBIT_ACCOUNT_CD`) REFERENCES `m_journal_account`(`ACCOUNT_CD`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `m_product_coa_mapping` ADD CONSTRAINT `m_product_coa_mapping_CREDIT_ACCOUNT_CD_fkey` FOREIGN KEY (`CREDIT_ACCOUNT_CD`) REFERENCES `m_journal_account`(`ACCOUNT_CD`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `t_trans_anggota` ADD CONSTRAINT `t_trans_anggota_NO_ANGGOTA_fkey` FOREIGN KEY (`NO_ANGGOTA`) REFERENCES `m_nasabah_anggota`(`NO_ANGGOTA`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `t_trans_tab` ADD CONSTRAINT `t_trans_tab_NO_TAB_fkey` FOREIGN KEY (`NO_TAB`) REFERENCES `m_nasabah_tab`(`NO_TAB`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `t_trans_jangka` ADD CONSTRAINT `t_trans_jangka_NO_JANGKA_fkey` FOREIGN KEY (`NO_JANGKA`) REFERENCES `m_nasabah_jangka`(`NO_JANGKA`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `t_trans_brahmacari` ADD CONSTRAINT `t_trans_brahmacari_NO_BRAHMACARI_fkey` FOREIGN KEY (`NO_BRAHMACARI`) REFERENCES `m_nasabah_brahmacari`(`NO_BRAHMACARI`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `t_trans_balimesari` ADD CONSTRAINT `t_trans_balimesari_NO_BALIMESARI_fkey` FOREIGN KEY (`NO_BALIMESARI`) REFERENCES `m_nasabah_balimesari`(`NO_BALIMESARI`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `t_trans_wanaprasta` ADD CONSTRAINT `t_trans_wanaprasta_NO_WANAPRASTA_fkey` FOREIGN KEY (`NO_WANAPRASTA`) REFERENCES `m_nasabah_wanaprasta`(`NO_WANAPRASTA`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `t_trans_kredit` ADD CONSTRAINT `t_trans_kredit_DEBITUR_KREDIT_ID_fkey` FOREIGN KEY (`DEBITUR_KREDIT_ID`) REFERENCES `m_debitur_kredit`(`DEBITUR_KREDIT_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
