/*
  Warnings:

  - A unique constraint covering the columns `[NO_PERMOHONAN]` on the table `m_debitur_kredit` will be added. If there are existing duplicate values, this will fail.

*/
-- AlterTable
ALTER TABLE `m_debitur_kredit` ADD COLUMN `METODE_ANGSURAN` VARCHAR(20) NULL,
    ADD COLUMN `MOHON_JANGKA_WAKTU` INTEGER NULL,
    ADD COLUMN `MOHON_SUKU_BUNGA` DECIMAL(5, 2) NULL,
    ADD COLUMN `NO_PERMOHONAN` VARCHAR(50) NULL,
    ADD COLUMN `SISTEM_BUNGA` VARCHAR(20) NULL;

-- CreateTable
CREATE TABLE `m_kredit_analisa` (
    `ANALISA_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `DEBITUR_KREDIT_ID` INTEGER NOT NULL,
    `POINT_CHARACTER` INTEGER NOT NULL,
    `URAIAN_CHARACTER` TEXT NULL,
    `POINT_CAPITAL` INTEGER NOT NULL,
    `URAIAN_CAPITAL` TEXT NULL,
    `POINT_CAPASITY` INTEGER NOT NULL,
    `URAIAN_CAPASITY` TEXT NULL,
    `POINT_CONDISION` INTEGER NOT NULL,
    `URAIAN_CONDISION` TEXT NULL,
    `POINT_COLATERAL` INTEGER NOT NULL,
    `URAIAN_COLATERAL` TEXT NULL,
    `SCORE` INTEGER NOT NULL,
    `REKOMENDASI` TEXT NULL,
    `CREATE_WHO` VARCHAR(50) NULL,
    `CREATE_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CHANGE_WHO` VARCHAR(50) NULL,
    `CHANGE_DATE` DATETIME(3) NULL,

    UNIQUE INDEX `m_kredit_analisa_DEBITUR_KREDIT_ID_key`(`DEBITUR_KREDIT_ID`),
    PRIMARY KEY (`ANALISA_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `m_debitur_colateral` (
    `COLATERAL_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NASABAH_ID` INTEGER NOT NULL,
    `JENIS_JAMINAN` VARCHAR(191) NOT NULL,
    `KETERANGAN` TEXT NULL,
    `NILAI_PASAR` DECIMAL(19, 4) NOT NULL,
    `NILAI_TAKASI` DECIMAL(19, 4) NOT NULL,
    `DETAIL_DATA` JSON NULL,
    `PHOTOS` TEXT NULL,
    `STATUS` VARCHAR(191) NOT NULL DEFAULT 'ACTIVE',
    `CREATE_WHO` VARCHAR(50) NULL,
    `CREATE_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CHANGE_WHO` VARCHAR(50) NULL,
    `CHANGE_DATE` DATETIME(3) NULL,

    PRIMARY KEY (`COLATERAL_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `m_kredit_colateral` (
    `DEBITUR_KREDIT_ID` INTEGER NOT NULL,
    `COLATERAL_ID` INTEGER NOT NULL,

    PRIMARY KEY (`DEBITUR_KREDIT_ID`, `COLATERAL_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `m_aktiva` (
    `ASSET_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAMA_AKTIVA` VARCHAR(191) NOT NULL,
    `NO_AKTIVA` VARCHAR(191) NOT NULL,
    `JENIS_AKTIVA` VARCHAR(191) NOT NULL,
    `TGL_PEROLEHAN` DATETIME(3) NOT NULL,
    `NILAI_PEROLEHAN` DECIMAL(19, 4) NOT NULL,
    `NILAI_RESIDU` DECIMAL(19, 4) NOT NULL,
    `MASA_MANFAAT` INTEGER NOT NULL,
    `PCT_PENYUSUTAN` DOUBLE NOT NULL,
    `METODE_PENYUSUTAN` VARCHAR(191) NOT NULL,
    `ACCOUNT_AKTIVA` VARCHAR(191) NOT NULL,
    `ACCOUNT_AKUM_PENY` VARCHAR(191) NOT NULL,
    `ACCOUNT_BIAYA_PENY` VARCHAR(191) NOT NULL,
    `STATUS` VARCHAR(191) NOT NULL DEFAULT 'ACTIVE',
    `CREATE_WHO` VARCHAR(50) NULL,
    `CREATE_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CHANGE_WHO` VARCHAR(50) NULL,
    `CHANGE_DATE` DATETIME(3) NULL,

    UNIQUE INDEX `m_aktiva_NO_AKTIVA_key`(`NO_AKTIVA`),
    PRIMARY KEY (`ASSET_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `t_aktiva_penyusutan` (
    `HISTORY_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ASSET_ID` INTEGER NOT NULL,
    `PERIODE` VARCHAR(191) NOT NULL,
    `NOMINAL` DECIMAL(19, 4) NOT NULL,
    `JOURNAL_ID` INTEGER NULL,
    `CREATE_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`HISTORY_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateIndex
CREATE UNIQUE INDEX `m_debitur_kredit_NO_PERMOHONAN_key` ON `m_debitur_kredit`(`NO_PERMOHONAN`);

-- AddForeignKey
ALTER TABLE `m_kredit_analisa` ADD CONSTRAINT `m_kredit_analisa_DEBITUR_KREDIT_ID_fkey` FOREIGN KEY (`DEBITUR_KREDIT_ID`) REFERENCES `m_debitur_kredit`(`DEBITUR_KREDIT_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `m_debitur_colateral` ADD CONSTRAINT `m_debitur_colateral_NASABAH_ID_fkey` FOREIGN KEY (`NASABAH_ID`) REFERENCES `m_nasabah`(`NASABAH_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `m_kredit_colateral` ADD CONSTRAINT `m_kredit_colateral_DEBITUR_KREDIT_ID_fkey` FOREIGN KEY (`DEBITUR_KREDIT_ID`) REFERENCES `m_debitur_kredit`(`DEBITUR_KREDIT_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `m_kredit_colateral` ADD CONSTRAINT `m_kredit_colateral_COLATERAL_ID_fkey` FOREIGN KEY (`COLATERAL_ID`) REFERENCES `m_debitur_colateral`(`COLATERAL_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `t_aktiva_penyusutan` ADD CONSTRAINT `t_aktiva_penyusutan_ASSET_ID_fkey` FOREIGN KEY (`ASSET_ID`) REFERENCES `m_aktiva`(`ASSET_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
