-- AlterTable
ALTER TABLE `s_menu_role_lpd` ADD COLUMN `can_create` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `can_delete` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `can_read` BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN `can_update` BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE `t_trans_anggota` ADD COLUMN `LATITUDE` DECIMAL(10, 8) NULL,
    ADD COLUMN `LONGITUDE` DECIMAL(10, 8) NULL;

-- AlterTable
ALTER TABLE `t_trans_balimesari` ADD COLUMN `LATITUDE` DECIMAL(10, 8) NULL,
    ADD COLUMN `LONGITUDE` DECIMAL(10, 8) NULL;

-- AlterTable
ALTER TABLE `t_trans_brahmacari` ADD COLUMN `LATITUDE` DECIMAL(10, 8) NULL,
    ADD COLUMN `LONGITUDE` DECIMAL(10, 8) NULL;

-- AlterTable
ALTER TABLE `t_trans_jangka` ADD COLUMN `LATITUDE` DECIMAL(10, 8) NULL,
    ADD COLUMN `LONGITUDE` DECIMAL(10, 8) NULL;

-- AlterTable
ALTER TABLE `t_trans_kredit` ADD COLUMN `LATITUDE` DECIMAL(10, 8) NULL,
    ADD COLUMN `LONGITUDE` DECIMAL(10, 8) NULL;

-- AlterTable
ALTER TABLE `t_trans_modal` ADD COLUMN `LATITUDE` DECIMAL(10, 8) NULL,
    ADD COLUMN `LONGITUDE` DECIMAL(10, 8) NULL;

-- AlterTable
ALTER TABLE `t_trans_tab` ADD COLUMN `LATITUDE` DECIMAL(10, 8) NULL,
    ADD COLUMN `LONGITUDE` DECIMAL(10, 8) NULL;

-- AlterTable
ALTER TABLE `t_trans_wanaprasta` ADD COLUMN `LATITUDE` DECIMAL(10, 8) NULL,
    ADD COLUMN `LONGITUDE` DECIMAL(10, 8) NULL;
