-- AlterTable
ALTER TABLE `t_posted_journal` ADD COLUMN `SOURCE_CODE` VARCHAR(20) NULL;

-- CreateTable
CREATE TABLE `t_posted_journal_temp` (
    `TEMP_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ORIGINAL_JOURNAL_ID` INTEGER NOT NULL,
    `JOURNAL_NO` VARCHAR(30) NOT NULL,
    `TGL_POSTING` DATE NOT NULL,
    `KETERANGAN` TEXT NULL,
    `POSTING_TYPE` VARCHAR(10) NOT NULL,
    `TRANS_TYPE` VARCHAR(30) NULL,
    `SOURCE_CODE` VARCHAR(20) NULL,
    `REF_ID` INTEGER NULL,
    `USER_ID` INTEGER NOT NULL,
    `WILAYAH_CD` VARCHAR(10) NULL,
    `STATUS` VARCHAR(20) NOT NULL,
    `DELETE_WHO` VARCHAR(50) NULL,
    `DELETE_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `DELETE_REASON` TEXT NULL,

    PRIMARY KEY (`TEMP_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `t_posted_journal_detail_temp` (
    `TEMP_DETAIL_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TEMP_JOURNAL_ID` INTEGER NOT NULL,
    `ACCOUNT_CD` VARCHAR(20) NOT NULL,
    `DEBIT` DECIMAL(19, 4) NOT NULL DEFAULT 0,
    `CREDIT` DECIMAL(19, 4) NOT NULL DEFAULT 0,
    `KETERANGAN` TEXT NULL,

    PRIMARY KEY (`TEMP_DETAIL_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `report_template` (
    `TEMPLATE_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TEMPLATE_CODE` VARCHAR(20) NOT NULL,
    `TEMPLATE_NAME` VARCHAR(255) NOT NULL,
    `DESCRIPTION` TEXT NULL,
    `PRODUCT_MODULE` VARCHAR(50) NOT NULL,
    `CATEGORY` VARCHAR(50) NOT NULL,
    `JSON_SCHEMA` JSON NOT NULL,
    `PAPER_SIZE` VARCHAR(20) NOT NULL DEFAULT 'A4',
    `ORIENTATION` VARCHAR(20) NOT NULL DEFAULT 'portrait',
    `CUSTOM_WIDTH` DECIMAL(10, 2) NULL,
    `CUSTOM_HEIGHT` DECIMAL(10, 2) NULL,
    `MARGIN_TOP` DECIMAL(10, 2) NOT NULL DEFAULT 20,
    `MARGIN_BOTTOM` DECIMAL(10, 2) NOT NULL DEFAULT 20,
    `MARGIN_LEFT` DECIMAL(10, 2) NOT NULL DEFAULT 20,
    `MARGIN_RIGHT` DECIMAL(10, 2) NOT NULL DEFAULT 20,
    `VERSION` INTEGER NOT NULL DEFAULT 1,
    `IS_DEFAULT` BOOLEAN NOT NULL DEFAULT false,
    `ACTIVE_FLAG` BOOLEAN NOT NULL DEFAULT true,
    `PARENT_ID` INTEGER NULL,
    `CREATE_WHO` VARCHAR(50) NULL,
    `CREATE_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CHANGE_WHO` VARCHAR(50) NULL,
    `CHANGE_DATE` DATETIME(3) NULL,

    UNIQUE INDEX `report_template_TEMPLATE_CODE_key`(`TEMPLATE_CODE`),
    PRIMARY KEY (`TEMPLATE_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `report_variable` (
    `VARIABLE_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PRODUCT_MODULE` VARCHAR(50) NOT NULL,
    `VARIABLE_KEY` VARCHAR(100) NOT NULL,
    `VARIABLE_NAME` VARCHAR(255) NOT NULL,
    `DATA_TYPE` VARCHAR(20) NOT NULL,
    `CATEGORY` VARCHAR(50) NOT NULL,
    `DESCRIPTION` TEXT NULL,
    `SAMPLE_VALUE` VARCHAR(255) NULL,
    `IS_ARRAY` BOOLEAN NOT NULL DEFAULT false,
    `FORMAT_OPTIONS` JSON NULL,
    `CREATE_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CHANGE_DATE` DATETIME(3) NULL,

    UNIQUE INDEX `report_variable_PRODUCT_MODULE_VARIABLE_KEY_key`(`PRODUCT_MODULE`, `VARIABLE_KEY`),
    PRIMARY KEY (`VARIABLE_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `report_generation_log` (
    `LOG_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TEMPLATE_ID` INTEGER NOT NULL,
    `RECORD_ID` VARCHAR(100) NULL,
    `FORMAT` VARCHAR(10) NOT NULL,
    `PARAMETERS` JSON NULL,
    `STATUS` VARCHAR(20) NOT NULL,
    `ERROR_MESSAGE` TEXT NULL,
    `FILE_PATH` VARCHAR(500) NULL,
    `FILE_SIZE` INTEGER NULL,
    `GENERATED_BY` VARCHAR(50) NULL,
    `GENERATED_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`LOG_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `passbook_print_state` (
    `STATE_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ACCOUNT_NUMBER` VARCHAR(50) NOT NULL,
    `PRODUCT_TYPE` VARCHAR(50) NOT NULL,
    `LAST_PRINTED_TRANS_ID` INTEGER NULL,
    `LAST_PRINTED_LINE` INTEGER NOT NULL DEFAULT 1,
    `TOTAL_LINES_PRINTED` INTEGER NOT NULL DEFAULT 0,
    `LAST_PRINT_DATE` DATETIME(3) NOT NULL,

    UNIQUE INDEX `passbook_print_state_ACCOUNT_NUMBER_key`(`ACCOUNT_NUMBER`),
    PRIMARY KEY (`STATE_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `t_posted_journal_detail_temp` ADD CONSTRAINT `t_posted_journal_detail_temp_TEMP_JOURNAL_ID_fkey` FOREIGN KEY (`TEMP_JOURNAL_ID`) REFERENCES `t_posted_journal_temp`(`TEMP_ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `report_template` ADD CONSTRAINT `report_template_PARENT_ID_fkey` FOREIGN KEY (`PARENT_ID`) REFERENCES `report_template`(`TEMPLATE_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `report_generation_log` ADD CONSTRAINT `report_generation_log_TEMPLATE_ID_fkey` FOREIGN KEY (`TEMPLATE_ID`) REFERENCES `report_template`(`TEMPLATE_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
