/*
  Warnings:

  - Added the required column `TGL_TRANS` to the `t_trans_kredit` table without a default value. This is not possible if the table is not empty.

*/
-- AlterTable
ALTER TABLE `m_debitur_jadwal` ADD COLUMN `BAYAR_BUNGA` DECIMAL(19, 4) NOT NULL DEFAULT 0,
    ADD COLUMN `BAYAR_DENDA` DECIMAL(19, 4) NOT NULL DEFAULT 0,
    ADD COLUMN `BAYAR_POKOK` DECIMAL(19, 4) NOT NULL DEFAULT 0,
    ADD COLUMN `DENDA` DECIMAL(19, 4) NOT NULL DEFAULT 0,
    ADD COLUMN `TOTAL_BAYAR` DECIMAL(19, 4) NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `t_trans_kredit` ADD COLUMN `BUNGA_BAYAR` DECIMAL(19, 4) NULL DEFAULT 0,
    ADD COLUMN `DENDA_BAYAR` DECIMAL(19, 4) NULL DEFAULT 0,
    ADD COLUMN `JOURNAL_ID` INTEGER NULL,
    ADD COLUMN `POKOK_BAYAR` DECIMAL(19, 4) NULL DEFAULT 0,
    ADD COLUMN `TGL_TRANS` DATE NOT NULL;
